"""
Django settings for ttytkvtl project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/
"""

from pathlib import Path
import os


# ========== BASE DIR ==========
BASE_DIR = Path(__file__).resolve().parent.parent


# ========== SECURITY ==========
# ⚠️ Lưu ý: khi triển khai production, SECRET_KEY nên được lấy từ biến môi trường
SECRET_KEY = 'django-insecure-@!r_*+k5vo0@)ihr40l8^)ze#c6w^kfb$3#7i5h(kzbj5b6adz'

DEBUG = False

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost'
    
]


# ========== APPLICATIONS ==========
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'ckeditor',
    'ckeditor_uploader',
    'import_export',
    'django.contrib.humanize',
    
]


# ========== MIDDLEWARE ==========
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'main.middleware.PageViewMiddleware',  # phải sau SessionMiddleware
    'django.middleware.locale.LocaleMiddleware',
]


# ========== URL & WSGI ==========
ROOT_URLCONF = 'ttytkvtl.urls'

WSGI_APPLICATION = 'ttytkvtl.wsgi.application'


# ========== TEMPLATES ==========
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.menu_items',
                'main.context_processors.sidebars',
                'main.context_processors.common_data',
                'main.context_processors.global_context',
                'main.context_processors.pageview_stats',
                'main.context_processors.schedule_context',
                'main.context_processors.sidebars_context',
                
            ],
        },
    },
]


# ========== DATABASE ==========
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ========== PASSWORD VALIDATORS ==========
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ========== INTERNATIONALIZATION ==========
LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('vi', 'Tiếng Việt'),
    ('en', 'English'),
]


# ========== STATIC & MEDIA ==========
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ========== CKEDITOR ==========
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'allowedContent': True,  # cho phép giữ nguyên class, style
        'toolbar': [
            ['Format', 'Bold', 'Italic', 'Underline', '-',
             'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock',
             '-', 'NumberedList', 'BulletedList',
             '-', 'Link', 'Unlink',
             '-', 'Image', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar',
             '-', 'Maximize', 'Source']
        ],
        'extraPlugins': ','.join([
            'justify',     # plugin căn lề
            'image2'       # plugin ảnh nâng cao (Image2)
        ]),
        'removeDialogTabs': 'image:advanced;link:advanced',
        'height': 300,
    }
}


# ========== UPLOAD LIMITS ==========
FILE_UPLOAD_MAX_MEMORY_SIZE = 1073741824  # tối đa 1GB
DATA_UPLOAD_MAX_MEMORY_SIZE = 1073741824  # form data tối đa 1GB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1073741824



# ========== DEFAULT PRIMARY KEY ==========
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

