# Generated by Django 5.1.2 on 2025-07-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Danh sách thông báo',
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên liên kết')),
                ('url', models.URLField(verbose_name='Liên kết')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='quicklinks/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Liên kết nhanh',
                'verbose_name_plural': 'Danh sách liên kết nhanh',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('youtube_url', models.URLField(verbose_name='Liên kết YouTube')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='Ảnh đại diện')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Danh sách video',
            },
        ),
    ]
