# Generated by Django 5.1.2 on 2025-07-28 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_menuitem_options_rename_title_menuitem_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Mục menu', 'verbose_name_plural': 'Các mục menu'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.article'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên URL (name trong urls.py)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên menu'),
        ),
    ]
