# Generated by Django 5.1.2 on 2025-07-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_menuitem_options_remove_menuitem_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='QuickLink',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
