# Generated by Django 5.1.2 on 2025-07-28 07:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sidebarleftitem_sidebarrightitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Nội dung')),
                ('external_link', models.URLField(blank=True, verbose_name='Link ngoài (nếu có)')),
                ('position', models.CharField(choices=[('left', 'Bên trái'), ('right', 'Bên phải')], default='left', max_length=10, verbose_name='Vị trí')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Mục Sidebar',
                'verbose_name_plural': 'Sidebar Trái/Phải',
                'ordering': ['position', 'ordering'],
            },
        ),
    ]
