# Generated by Django 5.1.2 on 2025-07-29 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sidebaritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tên Sidebar')),
            ],
            options={
                'verbose_name': 'Sidebar',
                'verbose_name_plural': 'Danh sách Sidebar',
            },
        ),
        migrations.AlterModelOptions(
            name='sidebaritem',
            options={'ordering': ['order'], 'verbose_name': 'Mục con trong Sidebar', 'verbose_name_plural': 'Danh sách mục con'},
        ),
        migrations.RenameField(
            model_name='sidebaritem',
            old_name='ordering',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='sidebaritem',
            name='content',
        ),
        migrations.RemoveField(
            model_name='sidebaritem',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='sidebaritem',
            name='position',
        ),
        migrations.AddField(
            model_name='sidebaritem',
            name='url',
            field=models.CharField(default=1, max_length=200, verbose_name='Liên kết'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sidebaritem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tiêu đề mục con'),
        ),
        migrations.AddField(
            model_name='sidebaritem',
            name='sidebar',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.sidebar'),
            preserve_default=False,
        ),
    ]
