# Generated by Django 5.1.2 on 2025-07-29 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sidebar_alter_sidebaritem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebaritem',
            name='sidebar',
        ),
        migrations.DeleteModel(
            name='SidebarLeftItem',
        ),
        migrations.DeleteModel(
            name='SidebarRightItem',
        ),
        migrations.DeleteModel(
            name='SideBar',
        ),
        migrations.DeleteModel(
            name='SidebarItem',
        ),
    ]
