# Generated by Django 5.1.2 on 2025-07-29 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_sidebaritem_sidebar_delete_sidebarleftitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tên Sidebar')),
            ],
            options={
                'verbose_name': 'Sidebar',
                'verbose_name_plural': 'Danh sách Sidebar',
            },
        ),
        migrations.CreateModel(
            name='SideBarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tiêu đề mục con')),
                ('url', models.CharField(max_length=200, verbose_name='Liên kết')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('sidebar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.sidebar')),
            ],
            options={
                'verbose_name': 'Mục con trong Sidebar',
                'verbose_name_plural': 'Danh sách mục con',
                'ordering': ['order'],
            },
        ),
    ]
