# Generated by Django 5.1.2 on 2025-07-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sidebar_sidebaritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='position',
            field=models.CharField(choices=[('left', 'Bên trái'), ('right', 'Bên phải')], default='left', max_length=10, verbose_name='Vị trí hiển thị'),
        ),
    ]
