# Generated by Django 5.1.2 on 2025-07-29 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sidebar_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebaritem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.sidebaritem'),
        ),
        migrations.AlterField(
            model_name='sidebaritem',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Liên kết'),
        ),
        migrations.CreateModel(
            name='SideBarPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài viết')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sidebar_posts/', verbose_name='Hình minh họa')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Đường dẫn ngoài')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='main.sidebaritem')),
                ('sidebar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.sidebar')),
            ],
            options={
                'verbose_name': 'Bài viết Sidebar',
                'verbose_name_plural': 'Danh sách bài viết Sidebar',
                'ordering': ['-created_at'],
            },
        ),
    ]
