# Generated by Django 5.1.2 on 2025-07-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_sidebaritem_parent_alter_sidebaritem_url_sidebarpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
