# Generated by Django 5.1.2 on 2025-07-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sidebarpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sidebar_posts/', verbose_name='Hình hiển thị'),
        ),
        migrations.AddField(
            model_name='sidebar',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Liên kết'),
        ),
    ]
