# Generated by Django 5.1.2 on 2025-07-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_sidebar_image_sidebar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Sidebar'),
        ),
    ]
