# Generated by Django 5.1.2 on 2025-07-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_sidebar_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarpost',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề bài viết'),
        ),
    ]
