# Generated by Django 5.1.2 on 2025-09-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_sidebarpost_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order'], 'verbose_name': 'Mục menu', 'verbose_name_plural': 'Các mục menu'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='article',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='main.article'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Thứ tự'),
        ),
    ]
