# Generated by Django 5.1.2 on 2025-09-12 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_menuitem_options_remove_menuitem_article_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bài viết', 'verbose_name_plural': 'Danh sách bài viết'},
        ),
        migrations.RemoveField(
            model_name='sidebar',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sidebar',
            name='url',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Hình minh họa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Đã xuất bản'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='main.article', verbose_name='Bài viết liên kết'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.menuitem', verbose_name='Menu cha'),
        ),
        migrations.AlterField(
            model_name='sidebaritem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.sidebaritem', verbose_name='Mục cha'),
        ),
        migrations.AlterField(
            model_name='sidebaritem',
            name='sidebar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.sidebar', verbose_name='Sidebar'),
        ),
        migrations.AlterField(
            model_name='sidebarpost',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='main.sidebaritem', verbose_name='Mục con'),
        ),
        migrations.AlterField(
            model_name='sidebarpost',
            name='sidebar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.sidebar', verbose_name='Sidebar'),
        ),
    ]
