# Generated by Django 5.1.2 on 2025-09-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_article_options_remove_sidebar_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebar',
            options={'ordering': ['order'], 'verbose_name': 'Sidebar', 'verbose_name_plural': 'Danh sách Sidebar'},
        ),
        migrations.AddField(
            model_name='sidebar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sidebar_images/', verbose_name='Hình đại diện'),
        ),
        migrations.AddField(
            model_name='sidebar',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AddField(
            model_name='sidebar',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Liên kết khi click'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Tiêu đề Sidebar'),
            preserve_default=False,
        ),
    ]
