# Generated by Django 5.1.2 on 2025-09-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_sidebar_options_sidebar_image_sidebar_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Hình ảnh')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Liên kết khi click')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự sắp xếp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Danh sách Banner',
                'ordering': ['order'],
            },
        ),
    ]
