# Generated by Django 5.1.2 on 2025-09-15 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_banner_options_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Danh sách Banner'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='main.menuitem', verbose_name='Chủ đề (Menu)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='Ảnh banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Liên kết khi click'),
        ),
    ]
