# Generated by Django 5.1.2 on 2025-09-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_banner_options_remove_menuitem_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Hiển thị trên menu'),
        ),
    ]
