# Generated by Django 5.1.2 on 2025-09-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_menuitem_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url_name',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='main.article', verbose_name='Bài viết liên kết'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='external_url',
            field=models.URLField(blank=True, help_text='Nếu chọn liên kết ngoài, nhập URL tại đây', max_length=500, null=True, verbose_name='Liên kết ngoài'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='link_type',
            field=models.CharField(choices=[('internal', 'Liên kết bài viết nội bộ'), ('external', 'Liên kết ngoài')], default='internal', max_length=10, verbose_name='Loại liên kết'),
        ),
    ]
