# Generated by Django 5.1.2 on 2025-09-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='articles/files/', verbose_name='Tệp đính kèm'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/', verbose_name='Hình minh họa'),
        ),
    ]
