# Generated by Django 5.1.2 on 2025-09-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_article_attachment_alter_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Trình duyệt')),
                ('path', models.CharField(max_length=255, verbose_name='Đường dẫn truy cập')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian truy cập')),
            ],
            options={
                'verbose_name': 'Lượt truy cập',
                'verbose_name_plural': 'Thống kê lượt truy cập',
                'ordering': ['-created_at'],
            },
        ),
    ]
