# Generated by Django 5.1.2 on 2025-09-16 01:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Nội dung'),
        ),
    ]
