# Generated by Django 5.1.2 on 2025-09-16 09:49

import autoslug.fields
import main.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=main.models.vn_slugify, unique=True),
        ),
        migrations.AlterField(
            model_name='sidebarpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=main.models.vn_slugify, unique=True),
        ),
    ]
