# Generated by Django 5.1.2 on 2025-09-17 07:07

import autoslug.fields
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Nội dung chữ chạy')),
                ('active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Chữ chạy (marquee)',
                'verbose_name_plural': 'Chữ chạy (marquee)',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=main.models.vn_slugify, unique=True),
        ),
    ]
