# Generated by Django 5.1.2 on 2025-09-17 07:15

import autoslug.fields
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_runningtext_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Tiêu đề ảnh')),
                ('caption', models.TextField(blank=True, verbose_name='Mô tả/ngắn gọn')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Ảnh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự sắp xếp')),
                ('active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Ảnh Carousel',
                'verbose_name_plural': 'Ảnh Carousel',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=main.models.vn_slugify, unique=True),
        ),
    ]
