# Generated by Django 5.1.2 on 2025-09-17 08:44

import autoslug.fields
import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_carouselimage_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhóm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Nhóm dịch vụ',
                'verbose_name_plural': 'Nhóm dịch vụ',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=main.models.vn_slugify, unique=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='STT')),
                ('name', models.CharField(max_length=255, verbose_name='Tên dịch vụ')),
                ('description', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('price_bhyt', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Mức giá do quỹ BHYT thanh toán')),
                ('price_non_bhyt', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Mức giá không thuộc quỹ BHYT thanh toán')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.servicecategory', verbose_name='Nhóm dịch vụ')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Danh mục dịch vụ & bảng giá',
                'ordering': ['category__name', 'order'],
            },
        ),
    ]
