# Generated by Django 5.1.2 on 2025-09-18 00:07

import autoslug.fields
import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_servicecategory_alter_category_slug_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhóm dịch vụ')),
            ],
            options={
                'verbose_name': 'Nhóm dịch vụ',
                'verbose_name_plural': 'Nhóm dịch vụ',
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Dịch vụ', 'verbose_name_plural': 'Dịch vụ'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=main.models.vn_slugify, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_bhyt',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Mức giá BHYT thanh toán'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_non_bhyt',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Mức giá không thuộc BHYT'),
        ),
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.servicegroup', verbose_name='Nhóm dịch vụ'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
