# Generated by Django 5.1.2 on 2025-09-18 01:01

import autoslug.fields
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='group',
        ),
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã tương đương'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=main.models.vn_slugify, unique=True),
        ),
        migrations.DeleteModel(
            name='ServiceGroup',
        ),
    ]
