# Generated by Django 5.1.2 on 2025-09-18 01:39

import autoslug.fields
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=main.models.vn_slugify, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_bhyt',
            field=models.IntegerField(verbose_name='Mức giá BHYT thanh toán'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_non_bhyt',
            field=models.IntegerField(verbose_name='Mức giá không thuộc BHYT'),
        ),
    ]
