# Generated by Django 5.1.2 on 2025-09-18 08:21

import autoslug.fields
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=main.models.vn_slugify, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_type',
            field=models.CharField(choices=[('internal', 'Liên kết bài viết nội bộ'), ('external', 'Liên kết ngoài'), ('static', 'Trang tĩnh')], default='internal', max_length=10, verbose_name='Loại liên kết'),
        ),
    ]
