# Generated by Django 5.1.2 on 2025-09-18 08:30

import autoslug.fields
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_category_slug_alter_menuitem_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, help_text='Nhập name của url trong urls.py', max_length=100, null=True, verbose_name='Tên urlpattern'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=main.models.vn_slugify, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_type',
            field=models.CharField(choices=[('internal', 'Liên kết bài viết nội bộ'), ('external', 'Liên kết ngoài'), ('named', 'Liên kết theo name')], default='internal', max_length=10, verbose_name='Loại liên kết'),
        ),
    ]
