# Generated by Django 5.1.2 on 2025-09-18 08:59

import autoslug.fields
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_menuitem_named_url_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Thông tin liên hệ', max_length=100, verbose_name='Tiêu đề')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('phone', models.CharField(max_length=50, verbose_name='Điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Giờ làm việc')),
                ('map_iframe', models.TextField(help_text='Dán toàn bộ mã iframe nhúng bản đồ Google Maps', verbose_name='Google Maps iframe')),
            ],
            options={
                'verbose_name': 'Thông tin liên hệ',
                'verbose_name_plural': 'Thông tin liên hệ',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=main.models.vn_slugify, unique=True),
        ),
    ]
