# Generated by Django 5.1.2 on 2025-09-23 00:36

import autoslug.fields
import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề khối')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Khối lịch khám',
                'verbose_name_plural': 'Các khối lịch khám',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=main.models.vn_slugify, unique=True),
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ví dụ: Thời gian, Địa điểm, Số điện thoại…', max_length=255, verbose_name='Tiêu đề dòng')),
                ('content', models.TextField(help_text='Ví dụ: Thứ Hai – Thứ Sáu: 07h00 – 11h00; 13h00 – 17h00', verbose_name='Nội dung chi tiết')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.schedulecategory')),
            ],
            options={
                'verbose_name': 'Dòng thông tin',
                'verbose_name_plural': 'Các dòng thông tin',
                'ordering': ['order'],
            },
        ),
    ]
