# Generated by Django 5.1.2 on 2025-09-23 01:44

import autoslug.fields
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_schedulecategory_alter_category_slug_scheduleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='is_red',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=main.models.vn_slugify, unique=True),
        ),
    ]
