# Generated by Django 5.1.2 on 2025-09-23 01:56

import autoslug.fields
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_scheduleitem_is_red_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecategory',
            name='main_title',
            field=models.CharField(default='LỊCH KHÁM BỆNH', help_text='Ví dụ: LỊCH KHÁM BỆNH / THỜI GIAN LÀM VIỆC', max_length=255, verbose_name='Tiêu đề chung'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=main.models.vn_slugify, unique=True),
        ),
    ]
