# Generated by Django 5.1.2 on 2025-09-23 03:50

import autoslug.fields
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulecategory',
            options={'ordering': ['main_title', 'order']},
        ),
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=main.models.vn_slugify, unique=True),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='content',
            field=models.TextField(verbose_name='Nội dung chi tiết'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề dòng'),
        ),
    ]
