# Generated by Django 5.1.2 on 2026-08-20 04:01

import autoslug.fields
import main.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_alter_schedulecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=main.models.vn_slugify, unique=True),
        ),
    ]
